### ISSUE TITLE
message format seems incorrect

### ISSUE THREAD

**Issue by akempe** [lhl/python-syslogssl#1]
This code really helped me, but I found it didn't work with Papertrail. I'm not sure if it's specific to them or not, but as you mention them (and because this is what I needed) it may be useful to others to know that the trailing character in this format doesn't work:

```
def emit(self, record):
    msg = self.format(record) + '\000'
```

Instead, for both TCP and TLS, the trailing character needs to be a linefeed as per page 7 of https://tools.ietf.org/html/rfc6587

> The ABNF for this is shown here:
> 
> ```
>    TCP-DATA = *SYSLOG-FRAME
>    SYSLOG-FRAME = SYSLOG-MSG TRAILER  ; non-transparent-framing
>                                       ; method
>    TRAILER = LF / APP-DEFINED
>    APP-DEFINED = 1*2OCTET
> ```

Changing to use `\n` works perfectly.

**Comment by lhl** [comment]
Ah thanks, this was originally ported straight from SysLogHandler https://bugs.python.org/issue12168 and I thought it worked w/ Papertrail when I ported it over. This repo has sort of been abandoned, but glad someone found it useful!
